### ISSUE TITLE
数字列表间距有点宽

### ISSUE THREAD

**Issue by punnpkin** [SprInec/typora-spring-theme#12]
自用的话调整哪块呢，看了半天没找到，这块想要调整一下

![Image](https://github.com/user-attachments/assets/67a4ac02-53c0-4c16-84b3-a40cac57fb66)

**Comment by SprInec** [comment]
若想减小间距，可以在 `spring.css` 文件的末尾添加以下代码，并通过减小 `5.7px` 这个值来调整间距

```css
p.md-end-block.md-p {
    padding: 0px 5.7px;
}
```
