### ISSUE TITLE
在设置了侧边栏序号和章节目录序号后，再改为spring主题，一级目录序号和一级目录内容重叠

### ISSUE THREAD

**Issue by AnboSkyWalker** [SprInec/typora-spring-theme#13]
一级目录序号和一级目录内容重叠
比如这个章节4，鼠标放上去后：
![Image](https://github.com/user-attachments/assets/7e9c2b57-f63e-497c-a111-d7fabbccd627)

比如这个章节10：
鼠标没有放上去

![Image](https://github.com/user-attachments/assets/0d7fe4d9-a206-4258-adda-5078806fb58e)

鼠标放上去后，可以看到10的叠影

![Image](https://github.com/user-attachments/assets/dbd96eac-9f4f-48ea-8775-31fd959e0beb)

二级目录正常
![Image](https://github.com/user-attachments/assets/86cae9ae-d7a8-4ef4-bbd7-0eef919c56e4)

配置侧边栏序号和章节目录序号来源：
https://pastebin.com/XmYgBbaz&usg=AOvVaw2ArbuayA5Mw8kQXR1F6xAw&opi=89978449
https://pastebin.com/FNYugSbXk&usg=AOvVaw1AdXQQgYtZnfNJFXyFhC_s&opi=89978449

**Comment by SprInec** [comment]
您好，你发的这两个`配置侧边栏序号和章节目录序号`的链接打开后没有内容

![Image](https://github.com/user-attachments/assets/2fb62dfb-a66e-4d37-8494-45b0693dc217)

能麻烦告知下您是如何配置所提到的侧边栏序号和章节目录序号吗🤗

**Comment by casuak** [comment]
把下面这段复制到css结尾就能自动编号

/*文章大纲自动编号*/
/**************************************
* Header Counters in TOC
**************************************/

/* No link underlines in TOC */
.md-toc-inner {
    text-decoration: none;
}

.md-toc-content {
    counter-reset: h1toc
}

.md-toc-h1 {
    margin-left: 0;
    font-size: 1.5rem;
    counter-reset: h2toc
}

.md-toc-h2 {
    font-size: 1.1rem;
    margin-left: 2rem;
    counter-reset: h3toc
}

.md-toc-h3 {
    margin-left: 3rem;
    font-size: .9rem;
    counter-reset: h4toc
}

.md-toc-h4 {
    margin-left: 4rem;
    font-size: .85rem;
    counter-reset: h5toc
}

.md-toc-h5 {
    margin-left: 5rem;
    font-size: .8rem;
    counter-reset: h6toc
}

.md-toc-h6 {
    margin-left: 6rem;
    font-size: .75rem;
}

.md-toc-h1:before {
    color: black;
    counter-increment: h1toc;
    content: counter(h1toc) ". "
}

.md-toc-h1 .md-toc-inner {
    margin-left: 0;
}

.md-toc-h2:before {
    color: black;
    counter-increment: h2toc;
    content: counter(h1toc) ". " counter(h2toc) ". "
}

.md-toc-h2 .md-toc-inner {
    margin-left: 0;
}

.md-toc-h3:before {
    color: black;
    counter-increment: h3toc;
    content: counter(h1toc) ". " counter(h2toc) ". " counter(h3toc) ". "
}

.md-toc-h3 .md-toc-inner {
    margin-left: 0;
}

.md-toc-h4:before {
    color: black;
    counter-increment: h4toc;
    content: counter(h1toc) ". " counter(h2toc) ". " counter(h3toc) ". " counter(h4toc) ". "
}

.md-toc-h4 .md-toc-inner {
    margin-left: 0;
}

.md-toc-h5:before {
    color: black;
    counter-increment: h5toc;
    content: counter(h1toc) ". " counter(h2toc) ". " counter(h3toc) ". " counter(h4toc) ". " counter(h5toc) ". "
}

.md-toc-h5 .md-toc-inner {
    margin-left: 0;
}

.md-toc-h6:before {
    color: black;
    counter-increment: h6toc;
    content: counter(h1toc) ". " counter(h2toc) ". " counter(h3toc) ". " counter(h4toc) ". " counter(h5toc) ". " counter(h6toc) ". "
}

.md-toc-h6 .md-toc-inner {
    margin-left: 0;
}

/**************************************
* Header Counters in Content
**************************************/

/** initialize css counter */
#write {
    counter-reset: h1
}

h1 {
    counter-reset: h2
}

h2 {
    counter-reset: h3
}

h3 {
    counter-reset: h4
}

h4 {
    counter-reset: h5
}

h5 {
    counter-reset: h6
}

/** put counter result into headings */
#write h1:before {
    counter-increment: h1;
    content: counter(h1) ". "
}

#write h2:before {
    counter-increment: h2;
    content: counter(h1) "." counter(h2) " "
}

#write h3:before, h3.md-focus.md-heading:before { /*override the default style for focused headings */
    counter-increment: h3;
    content: counter(h1) "." counter(h2) "." counter(h3) " "
}

#write h4:before, h4.md-focus.md-heading:before {
    counter-increment: h4;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) " "
}

#write h5:before, h5.md-focus.md-heading:before {
    counter-increment: h5;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) " "
}

#write h6:before, h6.md-focus.md-heading:before {
    counter-increment: h6;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) " "
}

/** override the default style for focused headings */
#write > h3.md-focus:before, #write > h4.md-focus:before, #write > h5.md-focus:before, #write > h6.md-focus:before, h3.md-focus:before, h4.md-focus:before, h5.md-focus:before, h6.md-focus:before {
    color: inherit;
    border: inherit;
    border-radius: inherit;
    position: inherit;
    left: initial;
    float: none;
    top: initial;
    font-size: inherit;
    padding-left: inherit;
    padding-right: inherit;
    vertical-align: inherit;
    font-weight: inherit;
    line-height: inherit;
}

/**************************************
* Header Counters in sidebar
**************************************/
.sidebar-content {
    counter-reset: h1
}

.outline-h1 {
    counter-reset: h2
}

.outline-h2 {
    counter-reset: h3
}

.outline-h3 {
    counter-reset: h4
}

.outline-h4 {
    counter-reset: h5
}

.outline-h5 {
    counter-reset: h6
}

.outline-h1 > .outline-item > .outline-label:before {
    counter-increment: h1;
    content: counter(h1) ". "
}

.outline-h2 > .outline-item > .outline-label:before {
    counter-increment: h2;
    content: counter(h1) "." counter(h2) " "
}

.outline-h3 > .outline-item > .outline-label:before {
    counter-increment: h3;
    content: counter(h1) "." counter(h2) "." counter(h3) " "
}

.outline-h4 > .outline-item > .outline-label:before {
    counter-increment: h4;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) " "
}

.outline-h5 > .outline-item > .outline-label:before {
    counter-increment: h5;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) " "
}

.outline-h6 > .outline-item > .outline-label:before {
    counter-increment: h6;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) " "
}

**Comment by SprInec** [comment]
抱歉前段时间有事好长时间没有上 github，这么久才回复您。该自动编号 css 中 h1 编号的代码与 SprIng 主题 h1 的 `#write h1:before`  样式冲突，故导致上述问题。目前该问题暂时无法修复，如果您希望应用自动编号功能可以尝试使用 [typora_plugin](https://github.com/obgnail/typora_plugin) 的 **auto_number** 插件。

**Comment by AnboSkyWalker** [comment]
太不好意思，今天才看到答复。我先临时将h1改为和h2一样的效果
```css
/* #write h1:before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: var(--write-h1-before-bg);
    transition: transform 0.4s ease;
    transform: scaleX(0);
    transform-origin: center;
    z-index: -1;
    display: calc(var(--h1-hover-effect) * var(--use-dynamic-effect));
}

#write h1:hover {
    transform: scale(calc(1 + 0.1 * var(--h1-hover-effect) * var(--use-dynamic-effect)));
}

#write h1:hover:before {
    transform: scaleX(calc(var(--h1-hover-effect) * var(--use-dynamic-effect)));
} */

#write h1:after,
#write h2:after {
    content: "";
    display: block;
    width: 30rem;
    height: 2.5px;
    margin: 0.5rem auto 0;
    background: var(--write-h2-after-bg);
    border-radius: 10px;
    transform: scaleX(0);
    transition:
        transform 0.4s ease,
        background 0.4s ease;
}

#write h1:hover:after,
#write h2:hover:after {
    transform: scaleX(calc(1 * var(--h2-after-effect) * var(--use-dynamic-effect)));
}
```

<img width="517" height="96" alt="Image" src="https://github.com/user-attachments/assets/745a10d5-f078-44c0-8424-c888c2aebc22" />

**Comment by ji-jl** [comment]
我通过插件实现的编号，也有类似问题，然后我让gemini改了下就没问题了

```css
#write h1 {
    position: relative; /* 确保伪元素定位正确 */
}

/* 将动效载体由 :before 改为 :after */
#write h1:after {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: var(--write-h1-before-bg);
    transition: transform 0.4s ease;
    transform: scaleX(0);
    transform-origin: center;
    z-index: -1;
    /* 保持原逻辑变量控制显示 */
    display: calc(var(--h1-hover-effect) * var(--use-dynamic-effect));
}

#write h1:hover {
    transform: scale(calc(1 + 0.1 * var(--h1-hover-effect) * var(--use-dynamic-effect)));
}

/* 悬浮时触发 :after 变形 */
#write h1:hover:after {
    transform: scaleX(calc(var(--h1-hover-effect) * var(--use-dynamic-effect)));
}
```
@SprInec
