### ISSUE TITLE
导出PDF字体对齐，以及图片代码块动态效果

### ISSUE THREAD

**Issue by xiaofu2730** [SprInec/typora-spring-theme#2]
作者大大，非常感谢您做出特别精美的主题！膜拜了!!!🤩🤩🤩
我在使用时候遇到了一些小问题请求帮助，期待回复：

1. 导出A4-pdf的时候好像文本是两端对齐的，好像有点类似word里面段落设置中的这一块🙌

![image](https://github.com/user-attachments/assets/8e1b550f-379e-4c0c-96ea-e01ea277bc53)

![image](https://github.com/user-attachments/assets/99b73cb5-3eb3-4115-bbf3-cb85c8eedd0c)

2. 在使用主题时候，代码块和图像的聚焦动效有个短暂的模糊到清晰的过程，感觉不是很流畅🙌

**Comment by SprInec** [comment]
您好呀🤗，很开心您能喜欢我设计的这个主题😊
以下是针对问题的回复~
1. SprIng 主题默认的对齐方式是两端对齐，如果您有其他需求可以通过以下方法修改对齐方式：
    1. 打开 `spring.css` 文件，找到如下代码（就在最开始的地方）（旧的 `spring.css` 文件没有注释，我会上传修改后的文件到 github 的✨）   
    ![image](https://github.com/user-attachments/assets/a08fb237-80e4-4d06-af16-f9782075c5bd)
    2. 根据需要修改对齐方式。
2. 这个动画效果存在模糊到清晰的过程是由于采用的 `scale()` 变化会将代码块的文字内容也进行过渡缩放，因此会存在叠影（模糊），旧版代码如下：
   ``` css
   @keyframes bounce-code {
    0%, 100% {
        transform: scale(1);
    }
    50% {
        transform: scale(1.01); 
    }
   ```
   优化后的代码如下：
    ``` css
    @keyframes bounce-code {
      0%, 100% {
        transform: translate(0, 0);
      }
      50% {
        transform: translate(-5px, -5px); 
      }
    }
    ```
    经过考虑我决定放弃缩放动画，通过使用微笑位移来模拟跳动的效果，经测试优化后的代码块悬停动画已不存在过渡内容模糊的情况。
    图片的缩放效果也是采用 `scale()` 进行的，但目前我未能找到其他可供替代的缩放方法，因此我缩短了动画的过渡时间，从而减少过渡模糊带来的影响。
**修改优化后的代码已上传 GitHub，请您下载体验最新的 SprIng 主题❤**
